# Generated by Django 6.0.5 on 2026-05-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingEvent',
        ),
    ]
